USE main_db;

DROP TABLE IF EXISTS scheduledata;

CREATE TABLE scheduledata(
	Id INT NOT NULL AUTO_INCREMENT,
    ScheduleDate DATE NOT NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    Location VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(250) NOT NULL,
	ScheduleMinutes INT NOT NULL,
	DateInserted DATETIME DEFAULT CURRENT_TIMESTAMP,
	DateUpdated DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    IsTaken BIT DEFAULT 0,
    DateDeleted DateTIME DEFAULT CURRENT_TIMESTAMP,
    UserId INT,
    CompanyId INT,
    PRIMARY KEY (Id),
    FOREIGN KEY (UserId) REFERENCES userdata(Id),
    FOREIGN KEY (CompanyId) REFERENCES companydata(Id)

)